CREATE TABLE LOGS (
    protocol varchar(5),
    response_time timestamp,
    elb_id varchar(45),
    client_address varchar(22),
    target_address varchar(22),
    request_processing_time real,
    target_processing_time real,
    response_processing_time real,
    elb_status_code smallint,
    target_status_code smallint,
    received_bytes integer,
    sent_bytes integer,
    request_method varchar(16),
    request_uri_path varchar(1024),
    request_uri_query varchar(1024),
    user_agent varchar(1024),
    ssl_cipher varchar(128),
    ssl_protocol varchar(128),
    target_group_arn varchar(128),
    trace_id varchar(128),
    domain_name varchar(128),
    chosen_cert_arn varchar(128)
);
